dist: trusty
language: c
compiler: gcc
cache: ccache
env:
  global:
   - TERM=dumb
addons:
   apt:
      packages:
        - bc 
        - wget
        - git
script:
        - bash -ex travis_build.sh

